import os

base_dir = "../../../output"
lib_dir = base_dir + '/lib'
inc_dir = base_dir + '/include'

# Add C++ Preprocessor
env = Environment(CPPFLAGS='-D_GNU_SOURCE -D__STDC_LIMIT_MACROS -DVERSION=\\\"1.0.0.0\\\" -DDEBUG')

# Add C compile-time flags
env.Append(CCFLAGS='-g -pipe -W -Wall')

#env.Append(CXXFLAGS='-g -pipe -W -Wall')

# Add header search path
env.Append(CPPPATH = [inc_dir])

# Add library search path
env.Append(LIBPATH = [lib_dir])

# Add libraries to link against
env.Append(LIBS = ['znetwork'])

# Add define
#env.Append(CPPDEFINES=['BIG_ENDIAN'])
# add define with value (e.g. -DRELEASE_BUILD=1)
#env.Append(CPPDEFINES={'RELEASE_BUILD' : '1'})

# Link time flags
env.Append(LINKFLAGS = ['-lpthread', '-lrt', '-Wl,--rpath,/usr/local/lib/'])

Default(env.Program(target = 'client', source = 'client.cpp'))
Default(env.Program(target = 'client_pool', source = 'client_poll.cpp'))
Default(env.Program(target = 'server', source = 'server.cpp'))


#for file in os.listdir(os.getcwd()) :
#    if os.path.isfile(os.path.join(os.getcwd(), file)) and file.find(".c") != -1:
#        bin_file = file[:file.rfind(".c")]
#        t = env.Program(target = bin_file, source = file)
#        Default(t)

