import os

omit_dirs = ['.', 'output', 'build']

# build all sub directory's targets
for sub_dir in os.listdir(os.getcwd()) :
    if os.path.isdir(os.path.join(os.getcwd(), sub_dir)) :
        if not sub_dir in omit_dirs :
            SConscript(sub_dir + '/SConscript', variant_dir= 'build/' + sub_dir)

